import 'package:flutter/material.dart';

const _map = <String, IconData>{
  'account_balance': Icons.account_balance,
  'ac_unit': Icons.ac_unit,
  'bolt': Icons.bolt,
  'breakfast_dining': Icons.breakfast_dining,
  'category': Icons.category,
  'checkroom': Icons.checkroom,
  'child_care': Icons.child_care,
  'child_friendly': Icons.child_friendly,
  'cleaning_services': Icons.cleaning_services,
  'cookie': Icons.cookie,
  'devices': Icons.devices,
  'directions_car': Icons.directions_car,
  'eco': Icons.eco,
  'egg_alt': Icons.egg_alt,
  'fitness_center': Icons.fitness_center,
  'flight': Icons.flight,
  'home': Icons.home,
  'inventory_2': Icons.inventory_2,
  'kitchen': Icons.kitchen,
  'local_cafe': Icons.local_cafe,
  'local_gas_station': Icons.local_gas_station,
  'local_grocery_store': Icons.local_grocery_store,
  'local_laundry_service': Icons.local_laundry_service,
  'local_pharmacy': Icons.local_pharmacy,
  'medical_services': Icons.medical_services,
  'nutrition': Icons.apple,
  'pets': Icons.pets,
  'receipt_long': Icons.receipt_long,
  'restaurant': Icons.restaurant,
  'restaurant_menu': Icons.restaurant_menu,
  'sanitizer': Icons.sanitizer,
  'school': Icons.school,
  'set_meal': Icons.set_meal,
  'smoking_rooms': Icons.smoking_rooms,
  'sports': Icons.sports,
};

IconData iconForName(String name) => _map[name] ?? Icons.category;
